const express = require('express');
const bodyParser = require('body-parser');
const app = express();
const PORT = 5000;



let player = [];
function guessGame()  {
		min = Math.ceil(1);
		max = Math.floor(25);
		return Math.floor(Math.random() * (max - min + 1) + min); // The maximum is inclusive and the minimum is inclusive
  }

let randInt = guessGame();


// let guessGame = () => {}
// function compareAgainstInput(array){
//   let val = array.length -1
//   if (array[val].p1 === array[val].randInt){
//     return 'PLAYER 1 WINS!'
//   }
//   if (array[val].p2 === array[val].randInt){
//     return 'PLAYER 2 WINS!'
//   }
//   ///// if less than or equal
//   if (array[val].p1 < array[val].randInt){
//     return 'Sorry, too low'
//   }

//   if (array[val].p2 < array[val].randInt){
//     return 'Sorry, too low'
//   }






  // if (inputA === ){
  //   return 'PLAYER 1 WINS!'
  // }
  // if (inputB === random){
  //   return 'PLAYER 2 WINS!'
  // }
  // if (inputA<random){
  //   return 'Sorry, too low'
  // }
  // if (inputA>random){
  //   return 'Sorry, too high'
  // }
  // if (inputB<random){
  //   return 'Sorry, too low'
  // }
  // if (inputB>random){
  //   return 'Sorry, too high'
  // }

// get this back to the client side???? HOWWWWWWWWWWW?!

// This must be added before GET & POST routes.
app.use(bodyParser.urlencoded({extended:true}))

// Serve up static files (HTML, CSS, Client JS)
app.use(express.static('server/public'));



app.get('/input', function(req, res){
  console.log('Request for info from /input')
// pretty sure comparison logic happens here or also gets sent here.
  // also send the result of higher or lower or the comparison of player[player.length -1].p1 & player[player.length -1].p2
  // against the random number generated by our function.
  //we can use a for loop in order for it to look at each object
  res.send(player);
  // res.send(player, compareAgainstInput(randInt, player[player.length-1].p1, ))
})


//store answer in variable and then add var to the the object and then
// pushing it alongside then (randInt)-
//push to the players array
app.post('/input', function(req, res){
  console.log('Adding info to /input')
  console.log(randInt);
  req.body.randInt = randInt


  if(Number(req.body.p1) === randInt) {
    req.body.p1_result = "Player 1 wins!!";
  }
  if (Number(req.body.p1) > randInt) {
		req.body.p1_result = "Sorry, too high :/";
  }
  if (Number(req.body.p1) < randInt) {
		req.body.p1_result = "Sorry, too low :/";
  }
  if (Number(req.body.p2) === randInt) {
		req.body.p2_result = "Player 2 wins!!";
  }
  if (Number(req.body.p2) > randInt) {
		req.body.p2_result = "Sorry, too high :/";
  }
  if (Number(req.body.p2) < randInt) {
		req.body.p2_result = "Sorry, too low :/";
  }

  player.push(req.body)

  res.sendStatus(201)

})


// GET & POST Routes go here


app.listen(PORT, () => {
  console.log ('Server is running on port', PORT)
})




